server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaodidemo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  mvc:
    static-path-pattern: /res/**


mybatis:
  configuration:
#    ��������̨��ӡsql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    �»���ת�շ�����
    map-underscore-to-camel-case: true
#  ����ɨ��
#  mapper-locations: classpath:mapper/*.xml
#  ����xml�Ľ������
#  type-aliases-package: net.htwater.xiaodiclass.domain


city2:
  id: 23
  fullName: cambrian
  name: cam
  shortName: ca



